### ISSUE TITLE
ui.apps filter.xml breaking other applications in /apps/cq 

### ISSUE THREAD

**Issue by richardliechty** [adobe/captivate-prime-aem-components#1]
### Expected Behaviour
Install package without affecting other installed applications.

### Actual Behaviour
The filter.xml of the ui.apps project includes the path /apps/cq which is also the installed location of acs-commons and acs-tools. Installing the Captivate Prime components package effectively deletes everything from the /apps/cq folder, wiping out the /apps/cq/core/content/nav/tools/acs-commons and /apps/cq/core/content/nav/tools/acs-tools folders, breaking those applications. 

### Reproduce Scenario (including but not limited to)
1. Install Adobe ACS Commons project and verify installation.
2. Install Captivate Prime AEM Components Package 1.2.0 (The behavior was the same in 1.0.x versions)
3. ACS Commons utilities are no longer accessible.

#### Platform and Version
AEM 6.5 (likely all)

#### Sample Code that illustrates the problem
ui.apps/src/main/content/META-INF/vault/filter.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<workspaceFilter version="1.0">
    <filter root="/apps/cpWidget"/>
    <filter root="/apps/cpWidget/components"/>
    <filter root="/apps/cpWidget/content"/>
    <filter root="/apps/cpWidget/install"/>
    <filter root="/apps/cq"/>
</workspaceFilter>
```

#### Proposed Solutuion

Update the ui.apps/src/main/content/META-INF/vault/filter.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<workspaceFilter version="1.0">
    <filter root="/apps/cpWidget"/>
    <filter root="/apps/cpWidget/components"/>
    <filter root="/apps/cpWidget/content"/>
    <filter root="/apps/cpWidget/install"/>
    <filter root="/apps/cq/core/content/nav/tools/cloudservices/cpwidgetconfig"/>
</workspaceFilter>
```

Add overlay paths to the ui.apps.structure/pom.xml to accommodate jackrabbit-filter validation.
```
<!-- Application overlay placeholder roots -->
<filter><root>/apps/cq/core</root></filter>
<filter><root>/apps/cq/core/content</root></filter>
<filter><root>/apps/cq/core/content/nav</root></filter>
<filter><root>/apps/cq/core/content/nav/tools</root></filter>
<filter><root>/apps/cq/core/content/nav/tools/cloudservices</root></filter>
<filter><root>/apps/cq/core/content/nav/tools/cloudservices/cpwidgetconfig</root></filter>
```

**Comment by prafulVaishnav** [comment]
Hi  @richardliechty Thanks for pointing out the issue along with the fix. The issue is addressed with 1.3.0 release.
