### ISSUE TITLE
Captivate Prime component throwing an Exception on author 

### ISSUE THREAD

**Issue by gakila** [adobe/captivate-prime-aem-components#2]
### Expected Behaviour
Upon drag and drop of the Captivate Prime Component (CPWidget), we should be able to edit and configure the component accordingly. 

### Actual Behaviour
SlingException error is being thrown. Error logs attached
[issue-dev-author-error.log](https://github.com/adobe/captivate-prime-aem-components/files/7340290/issue-dev-author-error.log)

#### Steps to Reproduce
1. Create a page with template. 
2. Drag drop the CPWidget component. 

#### Platform and Version
Adobe Experience Manager 6.5.7.0

#### Logs taken while reproducing problem
Error during include of component '/apps/cpWidget/components/content/widget' 
**Error Message:** 
org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: Identifier com.adobe.prime.core.sightly.models.EmbeddableWidgetModel cannot be correctly instantiated by the Use API 

Component path  =  /apps/cpWidget/components/content/widget 

**Full Exception:** 
See the logs attached.

**Comment by richardliechty** [comment]
Screengrab of the issue. It occurs when the component is added to the page.
![image](https://user-images.githubusercontent.com/1012829/137187589-00882fb4-5465-48fc-9cf9-af6475f98e61.png)

**Comment by prafulVaishnav** [comment]
Not received further comments/logs during internal communication, hence closing.
